### ISSUE TITLE
How to use it as an eloquent relationship

### ISSUE THREAD

**Issue by quarkmarino** [staudenmeir/laravel-cte#1]
Hey, I've discovered you package last week, Im tinkering with it right now, after installing mysql 8 (what a PITA), but i have a question, how would we use it as an eloquent relationship?, since I think the "belongsTo" and other relationships methods will not support it.

Thank you, I'll keep trying to make it work also, still learning mysql CTE.

**Comment by staudenmeir** [comment]
I've also thought about applications for the package, especially with recursive relationships.

What's an example where you would like to use CTEs as an Eloquent relationship?

**Comment by quarkmarino** [comment]
In my case I have the Employee Model, which can be transfered to another department, the transference is acomplished by replicating the model, changing the department that the replicated copy points to and also pointing the replicated copy to the old register (via a belongsTo "source" relationship)

```php
public function source()
{
  return $this->belongsTo(Self::class, 'employee_id');
}
```

In order to keep an history of all the previous positions. At some point I'll need to show the history of all the transferences from any point in the history chain, I've already tested that it works using a normal query builder and laravel-cte as shown in your usage guide, but I'd like to have is as a convenient eloquent relationship (lets say a "sources" that returns the history as a collection of Employees). However I've failed trying to use the "belongsTo" method within a sources relationship, since it keep using the default models table name (I think the belongsTo recreates a new instance from the parameter):

```sql
with recursive `sources` as ((select * from `employees` where `id` = ?) union all (select `employees`.* from `employees` inner join `sources` on `sources`.`source_id` = `employees`.`id`)) select * from `employees` where `employees`.`id` = ?
```

Even after passing an instance with a different table name to the belongsTo, and still not sure how to remove the "where" part

```php
$this->belongsTo((new Self())->setTable('sources'))->withRecursive...
```

Any way, I've ended encapsulating the CTE logic in a plain old method and calling it via sources()

```php
public function sources()
{
  $query = Self::whereId($this->employee_id) // Root element, base case
  ->unionAll(
    Self::select('employees.*')->join('sources', 'sources.employee_id', '=', 'employees.id')
  );
	
  return Self::from('sources')->withRecursiveExpression('sources', $query)->get();
}
```
maybe we can considered it "Solved", now, I have another problem that I'll address in another issue.

**Comment by staudenmeir** [comment]
https://github.com/laravel/framework/issues/27278 discusses the issue of custom table names.

Would you like to have a "real" relationship for features like eager loading?

**Comment by quarkmarino** [comment]
Oh, that would be sweet, but, for now I'm just gonna roll with it and experiment a little bit more in another CTE needs.

Thank you.

**Comment by staudenmeir** [comment]
Regarding your example: Is it important that you get the result in a single collection?

If not, you can also define a recursive relationship:

```php
public function source()
{
    return $this->belongsTo(Self::class, 'employee_id')->with('source');
}
```

This executes multiple queries, but works on all databases and is much simpler than using CTEs.

**Comment by quarkmarino** [comment]
Thank you, I've already thought about it and I'd really prefer a collection, since that would be easier to handle, intead of deeply nested chains of transferences, and that might create an explosion of queries for collections of Employees.

Thank you very much. I'll keep an eye on the package for that "real" relationship you mentioned.

**Comment by staudenmeir** [comment]
I'll take a look at it.

Please comment if you have more ideas for applications that the package could support.

**Comment by patrickomeara** [comment]
@staudenmeir this is a fantastic package. Thanks for your hard work.

I am interested in having a `HasMany` relationship. The app has an `employee` table which contains a `manager_id`. The levels can be infinite.

I'm trying to get the subordinates of a particular `Employee`.

Ideally 

```php
$manager = Employee(1);
$manager->subordinates;
```

would return a collection, I can add `lvl` in dynamically using

```php

$query = Employee::query()
    ->select('employees.*')
    ->addSelect(\DB::raw('1 lvl'))
    ->where('manager_id', $this->id)
    ->unionAll(
        Employee::query()
            ->select('employees.*')
            ->addSelect(\DB::raw('lvl+1'))
            ->join('tree', 'tree.id', '=', 'employees.manager_id')
    );

$descendants = Employee::query()
    ->from('tree')
    // SoftDeletes uses table name, this is a workaround
    ->withTrashed()
    ->whereNull('tree.deleted_at')
    ->withRecursiveExpression('tree', $query)
    ->orderBy('lvl')
    ->get();
```

Have you had any luck using relationship like this?

**Comment by staudenmeir** [comment]
@patrickomeara I'm working on a package for recursive relationships like yours, it's almost finished.

**Comment by staudenmeir** [comment]
I've released the new package: https://github.com/staudenmeir/laravel-adjacency-list

@quarkmarino 

```php
class Employee extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
    
    public function getParentKeyName()
    {
        return 'employee_id';
    }

    public function sources()
    {
        return $this->ancestors();
    }
}

$employee->sources;
```

@patrickomeara 

```php
class Employee extends Model
{
    use SoftDeletes, \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
    
    public function getParentKeyName()
    {
        return 'manager_id';
    }
    
    public function subordinates()
    {
        return $this->descendants()->breadthFirst();
    }
}

$employee->subordinates;
```

**Comment by staudenmeir** [comment]
@quarkmarino @patrickomeara Does the new package work for you? Are you missing any features?

**Comment by patrickomeara** [comment]
Yes! It is really well written.

One feature I have thought of is a hasOne relationship to the root ancestor (`parent_id` IS NULL) I imagine this would return itself if it were the root.

I'm still implementing it, I'll let you know if I hit any other issues.

**Comment by quarkmarino** [comment]
Sorry I disconected for a while, but I'm testing it today, thank you, I'll post the results.

**Comment by quarkmarino** [comment]
Working beautifuly so far, I can use it just as a normal relation, I'm thinking of some weird use cases, but ill try them and also check any of the other features before reporting anythin else. thank you again.

**Comment by staudenmeir** [comment]
Is the package working for you? Are you missing any features (besides the root ancestor relationship)?

**Comment by patrickomeara** [comment]
@staudenmeir yes, working well. 👍

**Comment by staudenmeir** [comment]
@patrickomeara The latest release adds a `RootAncestor` relation:
https://github.com/staudenmeir/laravel-adjacency-list#included-relationships

**Comment by patrickomeara** [comment]
Fantastic work @staudenmeir
