### ISSUE TITLE
Materialized cte

### ISSUE THREAD

**Issue by luciuz** [staudenmeir/laravel-cte#17]
Hello!

How to set 'materialized' option to an expression (cte)? Ty

**Comment by staudenmeir** [comment]
This is not possible at the moment, but I'll look into it.

**Comment by tpetry** [comment]
For PostgreSQL the third parameter of `withExpression` can be set to `[DB::raw('MATERIALIZED')]`. But this is only a trick for the current implementation, this may not work in a future release.

**Comment by staudenmeir** [comment]
I'll try to release this option in the next few weeks.

**Comment by staudenmeir** [comment]
I released a new version with materialized expressions
https://github.com/staudenmeir/laravel-cte/tree/materialized#materialized-expressions
