### ISSUE TITLE
Make package's logic scoped to queries via a config

### ISSUE THREAD

**Issue by piljac1** [staudenmeir/laravel-cte#18]
This is not a bug, but and enhancement/idea. I was wondering if it would be possible to have a flag or string based config to determine if we want all builders to be `Staudenmeir\LaravelCte\Query\Builder` on app load or if we want to manually specify when we want to use this specific builder type by the help of a specific Builder class (or maybe a trait?). For example (I'd leave the naming up to you):

```
CteBuilder::from('tree')
    ->withRecursiveExpression('tree', $query)
    ->get();
```

I currently don't like the fact that all builders are overwritten because it makes the package a huge project dependency and most of my existing phpdoc comment blocks obsolete.

**Comment by staudenmeir** [comment]
You can disable auto-discovery in your `composer.json`:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "staudenmeir/laravel-cte"
        ]
    }
},
```

And then instantiate the query builder manually:

```php
$builder = new \Staudenmeir\LaravelCte\Query\Builder(\DB::connection());

$result = $builder->from('tree')
    ->withRecursiveExpression('tree', $query)
    ->get();
```

Does that solve your issue?

**Comment by piljac1** [comment]
That works too ! Thanks 👍
