### ISSUE TITLE
Need help to make many to many relation work

### ISSUE THREAD

**Issue by krekas** [staudenmeir/laravel-cte#21]
Hi,
I need help to make this package work with many to many relation.

I have three basic tables
categories
| id  | name | parent_id |
| ------------- | ------------- | ------------- |
| 1  | root  | null  |
| 2  | sub 1  | 1  |
| 3  | sub 2  | 2  |

products
| id  | name |
| ------------- | ------------- |
| 1  | product 1  |
| 2  | product 2  |
| 3  | product 3  |

and category_product lets say
| category_id | product_id |
| ------------- | ------------- |
| 2 | 1 |
| 3 | 2 |
| 3 | 3 |

And I want to calculate how many products category has. So root would have 3 then sub1 would have also 3 and sub2 2 in this case.

What I have found on [laracasts](https://laracasts.com/discuss/channels/laravel/counting-total-products-from-parent-root-category?reply=617127) forum very similar solution but with different relation.
So now I have on Category model
```php
public function countTotalProducts()
    {
        $query = DB::table('categories')->selectRaw('categories.*')->where('id', $this->id)->unionAll(
		    DB::table('categories')->selectRaw('categories.*')->join('tree', 'tree.id', '=', 'categories.parent_id')
	    );
        $tree = DB::table('tree')->withRecursiveExpression('tree', $query)
            ->join('category_product', 'category_product.category_id', '=', 'tree.id')
            ->join('products', 'category_product.category_id', '=', 'tree.id')
            ->count('products.id');

        return $tree;
    }
```

In controller I do
```php
$this->categories = Category::where('parent_id', null)->get()->each(function(&$item) {
                $item->products_count = $item->countTotalProducts();
            });
```
witch of course gives wrong count result.
I'm new to laravel and harden queries so I need your help to make it work.
Thanks.

**Comment by staudenmeir** [comment]
Use this:

```php
public function countTotalProducts()
{
    $query = DB::table('categories')->selectRaw('categories.*')->where('id', 1)->unionAll(
        DB::table('categories')->selectRaw('categories.*')->join('tree', 'tree.id', '=', 'categories.parent_id')
    );

    $tree = DB::table('products')->withRecursiveExpression('tree', $query)
        ->join('category_product', 'category_product.product_id', '=', 'products.id')
        ->whereIn(
            'category_product.category_id',
            DB::table('tree')->select('id')
        )
        ->count('products.id');

    return $tree;
}
```

**Comment by krekas** [comment]
@staudenmeir thank for quick reply. It almost works. If I have more then one root category it only counts the first ones.

**Comment by staudenmeir** [comment]
I accidentally posted my test version with `->where('id', 1)`. Change it back to `->where('id', $this->id)`.

**Comment by krekas** [comment]
Thanks for the help.

**Comment by staudenmeir** [comment]
Also keep an eye on https://github.com/staudenmeir/laravel-adjacency-list/issues/45. It will vastly simplify this query by providing you with an Eloquent relationship for nested products that you can count, eager load etc.
