### ISSUE TITLE
How to use this with union based queries?

### ISSUE THREAD

**Issue by swichers** [staudenmeir/laravel-cte#24]
I have a report based query that needs to return multiple sets of data for different time ranges w/ associated labels. Using CTE lets me define what data I want to query against while the `UNION`s let me setup the specific ranges. This works great when working w/ MySQL directly.

When using this package to try and convert the query to Laravel, it does not seem possible to properly leverage `UNION` queries. The `with` statement gets included with the first `select`, and as soon as a union is added Laravel wraps both the initial `select` and the `with` in another `select`.

Minimal example:

```php
$q1 = DB::table('example')->where('col', true);
$q2 = DB::table('example')->where('col', false);

$q1->withExpression('example', function ($q) {
  $q->select('anything')->from('somewhere');
})
->union($q2)
->dump();
```

Output:

```
select * from (
  with "example" as (select "anything" from "somewhere") 
  select * from "example" where "col" = 1
) 
union 
select * from (select * from "example" where "col" = 0)
```

Expected:

```
with "example" as (select "anything" from "somewhere") 
select * from (select * from "example" where "col" = 1)
union 
select * from (select * from "example" where "col" = 0)
```

Is there a way to get this package to always put the `with` statement on the outermost part of the query?

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
I released new versions. You only need to move the `withExpression()` call after `union()`:

```php
$q1 = DB::table('example')->where('col', true);
$q2 = DB::table('example')->where('col', false);

$q1->union($q2)
->withExpression('example', function ($q) {
  $q->select('anything')->from('somewhere');
})
->dump();
```

**Comment by swichers** [comment]
Can confirm. The new queries generate as expected. :+1:
