### ISSUE TITLE
Change return type phpDoc of QueriesExpressions::newBaseQueryBuilder() 

### ISSUE THREAD

**Issue by vixducis** [staudenmeir/laravel-cte#26]
Currently, the [newBaseQueryBuilder](https://github.com/staudenmeir/laravel-cte/blob/edb3968cf636ef861125834a643cefb725590769/src/Eloquent/QueriesExpressions.php#L14) in QueriesExpressions has a return type of '\Illuminate\Database\Query\Builder'. Wouldn't it be beneficial to be more precise about the the exact return type and specify 'Staudenmeir\LaravelCte\Query\Builder'? This way, static code analysis tools and IDEs will actually pick up the additional methods provided by the extended class. 

I'd be happy to create a pull request if you'd like.

**Comment by vixducis** [comment]
Slightly different, but in the same vain: the first argument of [Builder::__construct()](https://github.com/staudenmeir/laravel-cte/blob/edb3968cf636ef861125834a643cefb725590769/src/Query/Builder.php#L39) expects \Illuminate\Database\Connection, while it would be cleaner to require \Illuminate\Database\ConnectionInterface. This would allow for different implementations of the interface, but still allow all functionality.

**Comment by staudenmeir** [comment]
> Currently, the newBaseQueryBuilder in QueriesExpressions has a return type of '\Illuminate\Database\Query\Builder'. Wouldn't it be beneficial to be more precise about the the exact return type and specify 'Staudenmeir\LaravelCte\Query\Builder'? This way, static code analysis tools and IDEs will actually pick up the additional methods provided by the extended class.

We can change that, but I don't think it's going to help IDEs since the method isn't called directly by the user and so the return type gets lost on the way.

> Slightly different, but in the same vain: the first argument of Builder::__construct() expects \Illuminate\Database\Connection, while it would be cleaner to require \Illuminate\Database\ConnectionInterface. This would allow for different implementations of the interface, but still allow all functionality.

I use the `Connection` class because the argument gets passed on and then the IDE no longer considers this line valid since the `getDriverName()` method is not part of the interface: 
https://github.com/staudenmeir/laravel-cte/blob/edb3968cf636ef861125834a643cefb725590769/src/Query/Builder.php#L57

**Comment by vixducis** [comment]
Oh, for the `Connection`-class: I totally overlooked that, my bad. Not possible to change that indeed.

But for the return type of newBaseQueryBuilder I still think it's a good idea to make the return type more specific. I could perfectly overload the method in my class that implements the trait, return an actual instance of `\Illuminate\Database\Query\Builder` (and not `Staudenmeir\LaravelCte\Query\Builder`) and break the functionality. I'm not a big fan of facades (let's not go into that 😅), so I'm using the function to get an instance of the builder. Probably not what it's meant for, but I find it to be quite nice.

**Comment by staudenmeir** [comment]
You're welcome to submit a PR.

**Comment by vixducis** [comment]
PR #28 was created. Thanks so much for your insights on this and for the package (it really helped me out).

**Comment by vixducis** [comment]
Thanks a lot!
