### ISSUE TITLE
mergeBindings not working

### ISSUE THREAD

**Issue by rajansharma3097** [staudenmeir/laravel-cte#27]
Hello Guys,

I'm facing an issue with mergeBindings() with withRecursiveExpression(). Following is the query that I'm trying to execute, kindly please help...

TblCalls::withRecursiveExpression('date_cte', function($query) use ($startDate, $endDate) {
                $query->selectRaw("CAST('$startDate' AS DATE) AS created_date")
                    ->unionAll(
                        DB::table('date_cte')
                        ->selectRaw("ADDDATE(created_date, INTERVAL 1 DAY)")
                        ->where([['created_date', '<', "'$endDate'"]])
                    );
            })
            ->selectRaw("created_date, successCalls,failedCalls")
            ->from(DB::raw(' ( ' . $subQuery->toSql() . ' ) AS X '))
            ->mergeBindings($subQuery->getQuery())
            ->groupBy('created_date')
            ->get();

Thanks in advance..

**Comment by staudenmeir** [comment]
What issue are you facing?

**Comment by rajansharma3097** [comment]
I'm getting the following error while running the above query:

Call to undefined method Staudenmeir\LaravelCte\Query\\Builder::getQuery()

Please help..

**Comment by staudenmeir** [comment]
How is `$subQuery` defined? You can replace `from()` and `mergeBindings()` with `fromSub()`:

```php
->fromSub($subQuery, 'X')
```

**Comment by rajansharma3097** [comment]
@staudenmeir thanks for your suggestion. Yes, after using `fromSub()`, query is working fine, but I'm getting only single record even though same query returning multiple rows in phpMyAdmin. And following is the `$subQuery`:

> $subQuery = DB::table('tbl_calls')->selectRaw("DATE_FORMAT(created_at,'%d-%M-%Y') AS created_date, SUM(IF((dial_call_status = 'completed' OR dial_call_status = 'recording'), 1, 0)) AS successCalls, SUM(IF(dial_call_status = 'no-answer', 1, 0)) AS failedCalls")
>         ->where([
>             ['user_id', $userId],
>             ['created_at', '<=', $startDate],
>             ['created_at', '>=', $endDate],
>             // ['campaign_name', 'like', "%$search%"]
>             ])
>         ->unionAll(
>             DB::table('date_cte')
>                 ->selectRaw('created_date, 0, 0')
>         )
>         ->groupBy('created_date');

**Comment by staudenmeir** [comment]
Did you compare the executed SQL with your query from phpMyAdmin? A difference I can see is that the query from the screenshot doesn't have a `user_id` constraint.

**Comment by rajansharma3097** [comment]
Yes, I did and both the queries are the same; I'm getting multiple records in phpMyAdmin. `user_id` constraint doesn't make a difference at the moment...

**Comment by staudenmeir** [comment]
Did you run the query without `['user_id', $userId],`? What's the executed SQL from the Laravel query?

**Comment by rajansharma3097** [comment]
Yes, I did. Following the raw query from Laravel query:

with recursive `date_cte` as ((select CAST('2021-09-03' AS DATE) AS created_date) union all (select ADDDATE(created_date, INTERVAL 1 DAY) from `date_cte` where (`created_date` < '2021-10-03'))) select created_date, successCalls,failedCalls from ((select DATE_FORMAT(created_at,'%d-%M-%Y') AS created_date, SUM(IF((dial_call_status = 'completed' OR dial_call_status = 'recording'), 1, 0)) AS successCalls, SUM(IF(dial_call_status = 'no-answer', 1, 0)) AS failedCalls from `tbl_calls` where (`created_at` <= '2021-09-03' AND `created_at` >= '2021-10-03') group by `created_date`) union all (select created_date, 0, 0 from `date_cte`)) as `X`

**Comment by staudenmeir** [comment]
At the end, `group by created_date` is missing: Is it not included in the SQL or did just not copy into the post?

**Comment by rajansharma3097** [comment]
Yup, I missed to copy the text.

**Comment by staudenmeir** [comment]
What result do you get when you run the raw SQL from phpMyAdmin in Laravel?

```php
dd(
    DB::select('with recursive `date_cte` ...')
);
```

**Comment by rajansharma3097** [comment]
Hi,

I've tried above and the following is the response:
array:31 [
  0 => {#1343
    +"created_date": "2021-09-03"
    +"successCalls": "0"
    +"failedCalls": "0"
  }
  1 => {#1344
    +"created_date": "2021-09-04"
    +"successCalls": "0"
    +"failedCalls": "0"
  }
  2 => {#1345
    +"created_date": "2021-09-05"
    +"successCalls": "0"
    +"failedCalls": "0"
  }
.
.
.]

But when I run the actual code, then got only:
array:1 [
  0 => array:3 [
    "created_date" => "2021-10-12"
    "successCalls" => "0"
    "failedCalls" => "0"
  ]
]

Following is the  Actual Code:

$subQuery = DB::table('tbl_calls')->selectRaw("DATE_FORMAT(created_at,'%d-%M-%Y') AS created_date, SUM(IF((dial_call_status = 'completed' OR dial_call_status = 'recording'), 1, 0)) AS successCalls, SUM(IF(dial_call_status = 'no-answer', 1, 0)) AS failedCalls")
        ->where([
            // ['user_id', $userId],
            ['created_at', '<=', $startDate],
            ['created_at', '>=', $endDate],
            // ['campaign_name', 'like', "%$search%"]
            ])
        ->unionAll(
            DB::table('date_cte')
                ->selectRaw('created_date, 0, 0')
        )
        ->groupBy('created_date');

TblCalls::withRecursiveExpression('date_cte', function($query) use ($startDate, $endDate) {
                $query->selectRaw("CAST('$startDate' AS DATE) AS created_date")
                    ->unionAll(
                        DB::table('date_cte')
                        ->selectRaw("ADDDATE(created_date, INTERVAL 1 DAY)")
                        ->where([['created_date', '<', "'$endDate'"]])
                    );
            })
            ->selectRaw("created_date, successCalls,failedCalls")
            // ->from(DB::raw(' ( ' . $subQuery->toSql() . ' ) AS X '))
            ->fromSub($subQuery, 'X')
            ->groupBy('created_date')
            ->get()->toArray();

Please help. Sorry for the late response.
