### ISSUE TITLE
Undefined Property ::$unionExpressions

### ISSUE THREAD

**Issue by waterbuckit** [staudenmeir/laravel-cte#29]
My model contains the SpatialTrait from Grimzy\LaravelMysqlSpatial and the HasRecursiveRelationships trait from your adjacency list package, but since 1.5.1, I am now getting this error:
```php
Undefined property: Grimzy\LaravelMysqlSpatial\Eloquent\BaseBuilder::$unionExpressions in .../vendor/staudenmeir/laravel-cte/src/Query/Grammars/CompilesExpressions.php on line 87
Undefined property: Grimzy\LaravelMysqlSpatial\Eloquent\BaseBuilder::$unionRecursionLimit in .../vendor/staudenmeir/laravel-cte/src/Query/Grammars/CompilesExpressions.php on line 91
```
Do you have any idea how to fix this? Have temporarily downgraded back to 1.5 for now. Thanks a lot.

**Comment by staudenmeir** [comment]
Thanks, I'll look into it.

**Comment by Healyhatman** [comment]
This is happening to me as well, on a simple ->whereHas()

**Comment by staudenmeir** [comment]
@Healyhatman Do you have any other traits in your model?

Can one of you share the whole stacktrace?

**Comment by Healyhatman** [comment]
I have SoftDeletes, FormAccessible, and \OwenIt\Auditing\Auditable on one, and the related I have Compoships and FormAccessible

 "message": "Undefined property: Awobaz\\Compoships\\Database\\Query\\Builder::$unionExpressions (View: C:\\inetpub\\wwwroot\\caremaster\\resources\\views\\client\\funding\\edit.blade.php)",
    "exception": "Facade\\Ignition\\Exceptions\\ViewException",
    "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\staudenmeir\\laravel-cte\\src\\Query\\Grammars\\CompilesExpressions.php",
    "line": 87,
    "trace": [
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\staudenmeir\\laravel-cte\\src\\Query\\Grammars\\CompilesExpressions.php",
            "line": 87,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\staudenmeir\\laravel-cte\\src\\Query\\Grammars\\SqlServerGrammar.php",
            "line": 23,
            "function": "compileSelectParent",
            "class": "Staudenmeir\\LaravelCte\\Query\\Grammars\\SqlServerGrammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 513,
            "function": "compileSelect",
            "class": "Staudenmeir\\LaravelCte\\Query\\Grammars\\SqlServerGrammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 212,
            "function": "whereExists",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "function": "Illuminate\\Database\\Query\\Grammars\\{closure}",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php",
            "line": 640,
            "function": "array_map"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 213,
            "function": "map",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 196,
            "function": "compileWheresToArray",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 91,
            "function": "compileWheres",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php",
            "line": 65,
            "function": "compileComponents",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\SqlServerGrammar.php",
            "line": 31,
            "function": "compileSelect",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\staudenmeir\\laravel-cte\\src\\Query\\Grammars\\CompilesExpressions.php",
            "line": 85,
            "function": "compileSelect",
            "class": "Illuminate\\Database\\Query\\Grammars\\SqlServerGrammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\staudenmeir\\laravel-cte\\src\\Query\\Grammars\\SqlServerGrammar.php",
            "line": 23,
            "function": "compileSelectParent",
            "class": "Staudenmeir\\LaravelCte\\Query\\Grammars\\SqlServerGrammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
            "line": 2301,
            "function": "compileSelect",
            "class": "Staudenmeir\\LaravelCte\\Query\\Grammars\\SqlServerGrammar",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
            "line": 2350,
            "function": "toSql",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
            "line": 2338,
            "function": "runSelect",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
            "line": 2872,
            "function": "Illuminate\\Database\\Query\\{closure}",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
            "line": 2339,
            "function": "onceWithColumns",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
            "line": 615,
            "function": "get",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
            "line": 599,
            "function": "getModels",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php",
            "line": 195,
            "function": "get",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\app\\ClientFundingLimit.php",
            "line": 178,
            "function": "get",
            "class": "Illuminate\\Database\\Eloquent\\Relations\\Relation",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 533,
            "function": "getTransactionsAttribute",
            "class": "App\\ClientFundingLimit",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 1695,
            "function": "mutateAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 414,
            "function": "transformModelValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 393,
            "function": "getAttributeValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php",
            "line": 2006,
            "function": "getAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\app\\ClientFundingLimit.php",
            "line": 201,
            "function": "__get",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 533,
            "function": "getTotalCheckedSumAttribute",
            "class": "App\\ClientFundingLimit",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 1695,
            "function": "mutateAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 414,
            "function": "transformModelValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php",
            "line": 393,
            "function": "getAttributeValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php",
            "line": 2030,
            "function": "getAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php",
            "line": 152,
            "function": "offsetExists",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\helpers.php",
            "line": 74,
            "function": "exists",
            "class": "Illuminate\\Support\\Arr",
            "type": "::"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php",
            "line": 988,
            "function": "data_get"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php",
            "line": 452,
            "function": "Illuminate\\Support\\Traits\\{closure}",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php",
            "line": 741,
            "function": "Illuminate\\Support\\Traits\\{closure}",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php",
            "line": 453,
            "function": "reduce",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\resources\\views/client/funding/edit.blade.php",
            "line": 130,
            "function": "sum",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php",
            "line": 107,
            "function": "require"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php",
            "line": 108,
            "function": "Illuminate\\Filesystem\\{closure}",
            "class": "Illuminate\\Filesystem\\Filesystem",
            "type": "::"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php",
            "line": 58,
            "function": "getRequire",
            "class": "Illuminate\\Filesystem\\Filesystem",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php",
            "line": 61,
            "function": "evaluatePath",
            "class": "Illuminate\\View\\Engines\\PhpEngine",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\facade\\ignition\\src\\Views\\Engines\\CompilerEngine.php",
            "line": 37,
            "function": "get",
            "class": "Illuminate\\View\\Engines\\CompilerEngine",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php",
            "line": 139,
            "function": "get",
            "class": "Facade\\Ignition\\Views\\Engines\\CompilerEngine",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php",
            "line": 122,
            "function": "getContents",
            "class": "Illuminate\\View\\View",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php",
            "line": 91,
            "function": "renderContents",
            "class": "Illuminate\\View\\View",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php",
            "line": 69,
            "function": "render",
            "class": "Illuminate\\View\\View",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php",
            "line": 35,
            "function": "setContent",
            "class": "Illuminate\\Http\\Response",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 794,
            "function": "__construct",
            "class": "Illuminate\\Http\\Response",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 763,
            "function": "toResponse",
            "class": "Illuminate\\Routing\\Router",
            "type": "::"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 695,
            "function": "prepareResponse",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php",
            "line": 78,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php",
            "line": 58,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php",
            "line": 67,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 697,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 672,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 636,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 625,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 166,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\app\\Http\\Middleware\\KeepActiveMiddleware.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\KeepActiveMiddleware",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\app\\Http\\Middleware\\SetDbConnectionMiddleware.php",
            "line": 19,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\SetDbConnectionMiddleware",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php",
            "line": 40,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php",
            "line": 86,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
            "line": 38,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\beyondcode\\laravel-server-timing\\src\\Middleware\\ServerTimingMiddleware.php",
            "line": 36,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "BeyondCode\\ServerTiming\\Middleware\\ServerTimingMiddleware",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 121,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 64,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 141,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\public\\index.php",
            "line": 54,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}

**Comment by staudenmeir** [comment]
I released a new version that fixes this issue.
