### ISSUE TITLE
How to use withRecursiveExpression when parent and child records are in the same table? 

### ISSUE THREAD

**Issue by Kenny417** [staudenmeir/laravel-cte#3]
I have the following MySQL query which I want to recreate using laravel-cte. 

```
with recursive cte (id, comment, parent_id) as (
  select     id,
             comment,
             parent_id
  from       comments
  where      parent_id = 37
  union all
  select     c.id,
             c.comment,
             c.parent_id
  from       comments c
  inner join cte
          on c.parent_id = cte.id
)
select * from cte;
```

Comments in my app can be children of other comments and in this query I am getting all of the child comments of the comment with the id 37, regardless of how deeply nested they are. 

I'm fairly new to laravel and I'm having a hard time wrapping my head around your `withRecursiveExpression()` example.

I came up with this but it returns all comments, not just children. 

```
$query = DB::table('comments')
->where('parent_id', '37')
->unionAll(
    DB::table('comments')
        ->select('comments.*')
        ->join('cte', 'cte.id', '=', 'comments.parent_id')
);

$comments = DB::table('comments')
    ->withRecursiveExpression('cte', $query)
    ->get();
```

Can you help me understand how to use laravel-cte with my use case?

**Comment by Kenny417** [comment]
Actually, I don't think I needed your package to do what I was attempting.  This seems to be working: 

```
select     id, comment, parent_id
from       comments
where      parent_id = 37
union all
select     c.id, c.comment, c.parent_id
from       comments c
inner join comments on c.parent_id = comments.id
```

and the php: 

```
$query = DB::table('comments')
    ->where('parent_id', '37')
    ->unionAll(
        DB::table('comments as C')
        ->select('comments.*')
        ->join('comments', 'C.id', '=', 'comments.parent_id')
    );
```

I'll run more checks to be sure, but I think I'm good.  I was overthinking this when I found your package.

**Comment by staudenmeir** [comment]
It's just a small typo:

```php
$comments = DB::table('cte')->withRecursiveExpression('cte', $query)->get();
                       ^^^
```

**Comment by Kenny417** [comment]
Wow that was simple.  Thanks for your help!

**Comment by staudenmeir** [comment]
I've released a new package for recursive relationships that might be useful to you: https://github.com/staudenmeir/laravel-adjacency-list

You can use it like this:

```php
class Comment extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
}

Comment::find(37)->descendants;
```
