### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Gui94** [staudenmeir/laravel-cte#30]
Hello,i'm trying to install in my project but i cound't figure it out what's happning,i've already searched and found nothing about it...how can i solve this problem?
I'm using laravel 8 and PhpMyAdmin
![image](https://user-images.githubusercontent.com/18669169/138321380-77f73aa8-5408-48fa-bf96-f4bbbc7b6295.png)

**Comment by staudenmeir** [comment]
This is an issue with PowerShell, please use `composer require staudenmeir/laravel-cte`.
