### ISSUE TITLE
insertUsing returns true instead of number of rows affected

### ISSUE THREAD

**Issue by Lundis** [staudenmeir/laravel-cte#36]
insertUsing() should return the number of rows inserted. It now returns true instead. I'm guessing this is an old laravel bug that was copy/pasted into laravel-cte?

laravel-cte's Builder:
`        return $this->connection->insert(`
laravel's Builder:
`        return $this->connection->affectingStatement(`

There are also other differences in the two functions, but I am not familiar enough with the Builder to say if they're intentional or not. laravel does applyBeforeQueryCallbacks() in pretty much all of the functions.

**Comment by staudenmeir** [comment]
Thanks! I released a new version.

I also added the `applyBeforeQueryCallbacks()` call, the method was only introduced last year.

**Comment by Lundis** [comment]
Thanks. We've verified that it works as expected on our end.
