### ISSUE TITLE
Add another package conflict to the list

### ISSUE THREAD

**Issue by petsoukos** [staudenmeir/laravel-cte#46]
After requiring the package (via dependency from [laravel-adjacency-list](https://github.com/petsoukos/laravel-adjacency-list)) my test suite stopped working throwing me an issue about geometry column types. It seems having this package with grimzy/laravel-mysql-spatial conflicts because both try to set the singleton 'db.factory'.

```
$this->app->singleton('db.factory', function ($app) {
    return new ConnectionFactory($app);
});
```
Any ideas how to solve this? I need both packages.

**Comment by staudenmeir** [comment]
Hi @petsoukos,
Please share the whole exception with its stacktrace. What is the failing test testing?
