### ISSUE TITLE
Issue with the new rawSql Laravel feature

### ISSUE THREAD

**Issue by dannewnsjump24** [staudenmeir/laravel-cte#47]
Hi Firstly let me say a huge thanks for creating this brilliant package, we've been using it on a build and was looking forward to using the new `toRawSql` feature that was merged in this week. After updating our code base and trying to use the method we get an error being thrown

`The database driver's grammar implementation does not support escaping values.`

After digging in and looking at the work that went into the Laravel [PR](https://github.com/laravel/framework/pull/46558) I can see that there has been some updates to the way the grammar classes now set and how they use the current connection. 

Dumping out the code just before it breaks in the new method I can see that the Laravel CTE Grammar class doesnt have a connection set. 

```
Staudenmeir\LaravelCte\Query\Grammars\MySqlGrammar {#1741 ▼ // vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2644
  #connection: null
  #tablePrefix: ""
  #operators: array:1 [▶]
  #bitwiseOperators: []
  #selectComponents: array:14 [▶]
}
```

after a quick look into this packages code I can see if I update the `BuildsExpressionQueries` Trait in particular this method 

```
 protected function getQueryGrammar(Connection $connection)
    {
        $driver = $connection->getDriverName();

        switch ($driver) {
            case 'mysql':
                return (new MySqlGrammar())->setConnection($connection);
            case 'pgsql':
                return new PostgresGrammar();
            case 'sqlite':
                return new SQLiteGrammar();
            case 'sqlsrv':
                return new SqlServerGrammar();
        }

        throw new RuntimeException('This database is not supported.'); // @codeCoverageIgnore
    }

    ```
    
    and use the new `setConnection` method this error then goes away and I can use the new method perfectly. I thought I would just let you know about the issue. Hopefully ive managed to explain the problem ok

**Comment by staudenmeir** [comment]
Hi @dannewnsjump24,
Thanks, I released a new version that resolves this.

**Comment by dannewnsjump24** [comment]
my word thank you so much @staudenmeir  for tackling it so quickly!
