### ISSUE TITLE
Oracle Driver (revived from #31)

### ISSUE THREAD

**Issue by wakjoko** [staudenmeir/laravel-cte#49]
hi @staudenmeir 

i'm looking into oracle since few days ago and after reading issue #31, i tried on my local with hints you provided in [oracle-laravel-6](https://github.com/staudenmeir/laravel-cte/tree/oracle-laravel-6) branch and i can confirm it is working fine.

just wondering, would you like to get oracle driver included in this package?

**Comment by staudenmeir** [comment]
Hi @wakjoko,
Absolutely, thanks for testing it. I closed the other ticket after not getting feedback for a year.

What Laravel version are you using?

**Comment by wakjoko** [comment]
I'm using the latest released version 10 for both laravel and yajra's oci8 package.

Additionally, i added conditional `return` based on db driver at [L16](https://github.com/staudenmeir/laravel-cte/blob/master/src/Eloquent/QueriesExpressions.php#L16).

Would be nicer if we can resolve the appropriate `Builder` class without the conditional `return` at all.

**Comment by staudenmeir** [comment]
> Additionally, i added conditional return based on db driver at [L16](https://github.com/staudenmeir/laravel-cte/blob/master/src/Eloquent/QueriesExpressions.php#L16).

Can you share this snippet?

**Comment by wakjoko** [comment]
mine look like this..
```php
protected function newBaseQueryBuilder()
{
    $connection = $this->getConnection();

    if($connection->getDriverName() === 'oracle') {
        return new OracleBuilder($connection);
    }

    return new Builder($connection);
}
```

**Comment by staudenmeir** [comment]
I created a new branch for Laravel 10. Please test it by updating the package version in your `composer.json`:

```json
"staudenmeir/laravel-cte": "dev-oracle-support",
```

**Comment by wakjoko** [comment]
looks good, will test it out tmr 😉

**Comment by wakjoko** [comment]
thanks!
cte queries works great with yajra oracle driver, smooth like you.
this is good to go but if you require unit testing, will have to spend another time on that part.

**Comment by staudenmeir** [comment]
I started with integration tests, but that's quite the adventure... I'll probably release it without tests for now.

For the [README](https://github.com/staudenmeir/laravel-cte#compatibility): Do you know the minimum Oracle version that supports CTEs? I didn't find that in their documentation.

**Comment by wakjoko** [comment]
WITH clause was introduced since Oracle 9.2 but I'm testing on Oracle 11g (2009), vs now it's 21c.

btw, yajra's oci8 package is updated well so I'm totally confident to release this feature without testing for now.

**Comment by staudenmeir** [comment]
Thanks. I released a new version with Oracle support.
