### ISSUE TITLE
Problem with pagination when using mssql

### ISSUE THREAD

**Issue by mz0lee** [staudenmeir/laravel-cte#5]
Hi, I'm trying to use your package in a laravel 5.5 app with mssql 2016 on the background and it works fine until I don't try to use it with the query builders pagination. The initial page loads without a problem but when I click on the second page it fails with the error: `SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near the keyword 'with'. (SQL: select * from (with [orders] ([OrderId]) as ...`. I think the problem is that the builder wraps the whole select while adding the offset statement breaking mssqls syntax of WHERE statement.

Could You please check on this? Thank You in advance! :)

**Comment by staudenmeir** [comment]
The issue is that SQL Server doesn't support common table expressions in subqueries. I'll look into it.

**Comment by staudenmeir** [comment]
The latest release fixes this.

**Comment by mz0lee** [comment]
And now it works like a charm :)
Thank You!
