### ISSUE TITLE
MSSQL CTE in Sub Query

### ISSUE THREAD

**Issue by andrewskm** [staudenmeir/laravel-cte#53]
As you know, MSSQL does not allow CTEs in sub queries.
Is there a way for the query to pass the expression up the chain so that it's applied at the beginning?

For my use case, I query a list that uses a CTE.
In reports, I need to aggregate calculations based on data in that list, so I throw the list query in a new subquery and apply selects.

The work around for this would be to pass the CTE query along with the base query so that I manually call the `withExpression` method on the list query and then the aggregates query.

Figured I'd ask, just in case.

**Comment by staudenmeir** [comment]
Hi @andrewskm,
What does your query look like?

**Comment by andrewskm** [comment]
This is a very basic example of what I have:
```php
$billingsQuery = Organization::query()
     ->withExpression('organization_profile_billings_cte', (new OrganizationProfileUtilityBilling)())
     ->join('organization_profile_billings_cte', 'organization_profile_billings_cte.organization_id', '=', 'core_organizations.id')
     ->where('name', 'Bruen Plaza');

$topQuery = \DB::query()
               ->selectRaw('*')
               ->fromSub($billingsQuery, 'billings');
```

Which produces the incorrect SQL (`with` is inside the `from`):
```sql
select *
from (
    with [organization_profile_billings_cte] as (
        select [organization_profile_utility_billings].*, [organization_profiles].[organization_id]
        from [organization_profiles]
        inner join [core_organizations] on [core_organizations].[id] = [organization_profiles].[organization_id]
        inner join [organization_profile_utility_billings] on [organization_profile_utility_billings].[organization_profile_id] = [organization_profiles].[id]
    )
    select *
    from [core_organizations]
    inner join [organization_profile_billings_cte] on [organization_profile_billings_cte].[organization_id] = [core_organizations].[id]
    where [name] = 'Bruen Plaza' and [core_organizations].[deleted_at] is null
) as [billings]

```

**Comment by staudenmeir** [comment]
> In reports, I need to aggregate calculations based on data in that list, so I throw the list query in a new subquery and apply selects.

What does this part look like / how would you like to implement it?

**Comment by andrewskm** [comment]
> $topQuery = \DB::query()
               ->selectRaw('*')
               ->fromSub($billingsQuery, 'billings');

Exactly like this, except with selects to aggregate whatever is needed, ex: `->selectRaw('sum(cost) * sum(consumption)')`

**Comment by staudenmeir** [comment]
Did you try the CTE on the top query? This should work since the CTE is uncorrelated.

```php
$billingsQuery = Organization::query()
     ->join('organization_profile_billings_cte', 'organization_profile_billings_cte.organization_id', '=', 'core_organizations.id')
     ->where('name', 'Bruen Plaza');

$topQuery = \DB::query()
               ->withExpression('organization_profile_billings_cte', (new OrganizationProfileUtilityBilling)())
               ->selectRaw('sum(cost) * sum(consumption)')
               ->fromSub($billingsQuery, 'billings');
```

**Comment by andrewskm** [comment]
Yes, that works, but my use case has the expression on the sub query since that is used first for a paginated list.

Most of the time the top level query isn't in the same method, so I pass along the base query to it afterwards in order to not be redundant in creating queries.

**Comment by staudenmeir** [comment]
Hard to say without knowing the whole setting, but I'll try.

Since `fromSub()` compiles the subquery into SQL, you need to move the CTE beforehand:

```php
$topQuery = DB::query();

$topQuery->expressions = $billingsQuery->getQuery()->expressions;
$topQuery->setBindings($billingsQuery->getQuery()->getRawBindings()['expressions'], 'expressions');

$billingsQuery->getQuery()->expressions = [];
$billingsQuery->getQuery()->setBindings([], 'expressions');

$topQuery->selectRaw('sum(cost) * sum(consumption)')
     ->fromSub($billingsQuery, 'billings');
```

**Comment by andrewskm** [comment]
That was essentially the plan, I just wanted to make sure there weren't any known alternatives.

Thanks for taking the time to look into this.

**Comment by staudenmeir** [comment]
If you need this behavior in multiple places, you could define a custom query builder class and override `fromSub()` to automatically move CTEs up to that parent query. But that's as "elegant" as it gets.
