### ISSUE TITLE
Firebird Support

### ISSUE THREAD

**Issue by gssj85** [staudenmeir/laravel-cte#54]
Please add support for Firebird.

**Comment by staudenmeir** [comment]
Hi @gssj85,
I remember your ticket from last year. Did you start working on a PR?

**Comment by gssj85** [comment]
> Hi @gssj85, I remember your ticket from last year. Did you start working on a PR?

Nah man I would like to but I don't even know where to start, lacking some basic knowledge...

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by gssj85** [comment]
Thanks man, sent you a message on Twitter (X)

**Comment by staudenmeir** [comment]
I've released a new version with support for Firebird.
