### ISSUE TITLE
Call to undefined method Staudenmeir\LaravelCte\Query\Builder::leftJoinLateral()

### ISSUE THREAD

**Issue by iamrangoo** [staudenmeir/laravel-cte#55]
On Laravel 10, when trying to use leftJoinLateral:
https://laravel.com/docs/10.x/queries#left-join-right-join-clause

I get this error:
Call to undefined method Staudenmeir\LaravelCte\Query\Builder::leftJoinLateral()

My code looks like:
`
use Illuminate\Support\Facades\DB;
Route::get('/getfights', function(){
        $sub = DB::query()
            ->fromSub(function($query){
                $query->select('id')
                    ->selectRaw('count(CASE WHEN winner_id = id THEN 1 END) as wins')
                    ->selectRaw('count(*) - count(CASE WHEN winner_id = id THEN 1 END) - count(CASE WHEN winner_id is null THEN 1 END) as loss')
                    ->selectRaw('count(CASE WHEN winner_id is null THEN 1 END) as other')
                    ->fromSub(function($query){
                        $query->select('id', 'winner_id')
                            ->from('events')
                            ->orderBy('date', 'desc')
                            ->take(5);
                    }, 'recent')
                    ->groupBy('id');
            }, 'recent')
            ->whereColumn('id', 'fighters.some_id');

        $fighters = DB::table('fighters')
            ->leftJoinLateral($sub, 'recent')
            ->get();
});
`

**Comment by iamrangoo** [comment]
hi @staudenmeir , it's 10.32.1

**Comment by staudenmeir** [comment]
Lateral joins were only added in Laravel [10.46.0](https://github.com/laravel/framework/releases/tag/v10.46.0).

**Comment by iamrangoo** [comment]
@staudenmeir ah, thanks so much for looking in to that. Sorry, I'll make sure to double check my version next time!
