### ISSUE TITLE
Call to undefined method Staudenmeir\LaravelCte\Query\Builder::insertReturning()

### ISSUE THREAD

**Issue by sawirricardo** [staudenmeir/laravel-cte#56]
https://flareapp.io/share/V7jdkGom

I'm using this package in combination with https://github.com/tpetry/laravel-postgresql-enhanced. Is this a conflict?

**Comment by staudenmeir** [comment]
Hi @sawirricardo,
I recommend that you remove this package use the other one's CTE feature:
https://github.com/tpetry/laravel-postgresql-enhanced?tab=readme-ov-file#common-table-expressions-cte

**Comment by sawirricardo** [comment]
@staudenmeir  How about your other package such as `laravel-adjacency-list`?

**Comment by staudenmeir** [comment]
Try disabling auto-discovery for this package:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "staudenmeir/laravel-cte"
        ]
    }
},
```

Then run `composer dump`.
