### ISSUE TITLE
Wrong return type of QueriesExpressions::newBaseQueryBuilder()

### ISSUE THREAD

**Issue by devantoine** [staudenmeir/laravel-cte#57]
Hello,

I'm trying to have my IDE figuring out the added query builder's methods such as `withExpression()`.

I've noticed that the return type of `QueriesExpressions::newBaseQueryBuilder()` is set to `\Illuminate\Database\Query\Builder` while it returns a `Staudenmeir\LaravelCte\Query\Builder` object.

[There was a PR](https://github.com/staudenmeir/laravel-cte/pull/28/files) fixing that typing issue which then was reverted by this PR: https://github.com/staudenmeir/laravel-cte/pull/50/files

It won't fix the IDE code completion when using `DB` facades but at least it'll work when calling `QueriesExpressions::newBaseQueryBuilder()`.

**Comment by staudenmeir** [comment]
Hi @devantoine,
Not sure why I reverted that, looks like a merge regression (the PR was based on a pretty old branch). I'll look into it.

**Comment by staudenmeir** [comment]
I released a new version that restores the return type.
